// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpeedrunAuditingApi.Contexts;

#nullable disable

namespace SpeedrunAuditingApi.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20241011222624_DefaultValueForCreatedAtTattoo")]
    partial class DefaultValueForCreatedAtTattoo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("SpeedrunAuditingApi.Models.EliteEmployee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsElite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EliteEmployees");
                });

            modelBuilder.Entity("SpeedrunAuditingApi.Models.EliteEmployee", b =>
                {
                    b.OwnsOne("SpeedrunAuditingApi.Models.Audit", "Audit", b1 =>
                        {
                            b1.Property<Guid>("EliteEmployeeId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("CreatedAt")
                                .HasColumnType("TEXT");

                            b1.Property<Guid?>("CreatedBy")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("TEXT");

                            b1.Property<Guid?>("UpdatedBy")
                                .HasColumnType("TEXT");

                            b1.HasKey("EliteEmployeeId");

                            b1.ToTable("EliteEmployees");

                            b1.WithOwner()
                                .HasForeignKey("EliteEmployeeId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
