// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpeedrunAuditingApi.Contexts;

#nullable disable

namespace SpeedrunAuditingApi.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20241011022455_AddedCreditCards")]
    partial class AddedCreditCards
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("SpeedrunAuditingApi.Models.CreditCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BankName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cvc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Expiry")
                        .HasColumnType("TEXT");

                    b.Property<string>("HolderName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CreditCards");
                });

            modelBuilder.Entity("SpeedrunAuditingApi.Models.CreditCard", b =>
                {
                    b.OwnsOne("SpeedrunAuditingApi.Models.Audit", "Audit", b1 =>
                        {
                            b1.Property<Guid>("CreditCardId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("CreatedAt")
                                .HasColumnType("TEXT");

                            b1.Property<Guid?>("CreatedBy")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("TEXT");

                            b1.Property<Guid?>("UpdatedBy")
                                .HasColumnType("TEXT");

                            b1.HasKey("CreditCardId");

                            b1.ToTable("CreditCards");

                            b1.WithOwner()
                                .HasForeignKey("CreditCardId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
